name: tests

on:
  push:
    branches:
      - main
  pull_request: {}
jobs:
  tests:
    runs-on: ubuntu-22.04

    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options: --entrypoint redis-server

    strategy:
      fail-fast: true
      matrix:
        php: [8.2, 8.3]
        laravel: [9, 10, 11]
        include:
          - laravel: 9
            php: 8.0
            testbench: 7
          - laravel: 10
            testbench: 8
          - laravel: 11
            testbench: 9
          

    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }} - Testbench ${{ matrix.testbench }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: curl, dom, gd, json, libxml, mbstring, zip
          ini-values: error_reporting=E_ALL
          tools: composer:v2
          coverage: none

      - name: Install dependencies
        run: |
          composer require "orchestra/testbench=^${{ matrix.testbench }}" "laravel/framework=^${{ matrix.laravel }}" --dev --no-update
          composer update --prefer-dist --no-interaction --no-progress

      - name: Execute tests
        run: vendor/bin/pest
